/* Indiana Permit Quest: question bank
 * Every question is grounded in the Indiana Driver's Manual (BMV).
 * ref = manual chapter and page, e.g. "Ch. 6, p. 27".
 */
const QUESTIONS = [
/* ---------- SIGNS AND SIGNALS ---------- */
{ cat: "Signs & Signals",
  q: "What does a red background on a traffic sign mean?",
  options: [
    "It shows road services and evacuation routes",
    "It conveys a regulation that requires immediate action",
    "It warns of temporary construction conditions",
    "It gives directions and distances"
  ],
  answer: 1,
  why: "The manual says red signs convey traffic regulations that require drivers to take immediate action, like a Wrong Way sign.",
  ref: "Ch. 6, p. 27" },
{ cat: "Signs & Signals",
  q: "You see a yellow sign that says Slippery When Wet. What is it warning you about?",
  options: [
    "A regulation you must obey immediately",
    "A recreational site nearby",
    "A specific road condition or hazard ahead",
    "A temporary detour route"
  ],
  answer: 2,
  why: "Yellow signs prepare drivers for specific road conditions and hazards ahead. Slippery When Wet is the manual's example.",
  ref: "Ch. 6, p. 27" },
{ cat: "Signs & Signals",
  q: "A sign with a white background, like a speed limit sign, is telling you what?",
  options: [
    "A suggested speed for good weather",
    "A traffic regulation you must obey",
    "The distance to the next town",
    "A warning about a hazard ahead"
  ],
  answer: 1,
  why: "White signs display traffic regulations, such as speed limits, that drivers must obey.",
  ref: "Ch. 6, p. 27" },
{ cat: "Signs & Signals",
  q: "Orange traffic signs, such as a Flagger Ahead sign, warn you about what?",
  options: [
    "Permanent speed limit changes",
    "Temporary traffic conditions like construction",
    "Nearby state parks",
    "School zones"
  ],
  answer: 1,
  why: "Orange signs warn of temporary traffic conditions, often from highway construction and maintenance projects.",
  ref: "Ch. 6, p. 27" },
{ cat: "Signs & Signals",
  q: "A green sign showing the distance to the next city tells you what kind of information?",
  options: [
    "A regulation requiring immediate action",
    "Permitted movements, directions, or guidance",
    "A warning about a road hazard",
    "Road services at the next exit"
  ],
  answer: 1,
  why: "Green signs indicate permitted movements and directions or guidance, such as highway entrances, exits, or distance to destinations.",
  ref: "Ch. 6, p. 27" },
{ cat: "Signs & Signals",
  q: "A blue sign advertising gas and food at the next exit is showing you what?",
  options: [
    "Road services and evacuation route information",
    "A recreational area nearby",
    "A construction zone ahead",
    "A regulation you must obey"
  ],
  answer: 0,
  why: "Blue signs display road services and evacuation route information, like amenities at an upcoming exit.",
  ref: "Ch. 6, p. 27" },
{ cat: "Signs & Signals",
  q: "A brown sign pointing to a state park indicates what?",
  options: [
    "A nearby recreational or cultural interest site",
    "A school zone",
    "A temporary traffic condition",
    "A railroad crossing"
  ],
  answer: 0,
  why: "Brown signs indicate nearby recreational and cultural interest sites.",
  ref: "Ch. 6, p. 27" },
{ cat: "Signs & Signals",
  q: "A circular traffic sign alerts you to what ahead?",
  options: [
    "A school zone",
    "A yield intersection",
    "An upcoming railroad crossing",
    "A no-passing zone"
  ],
  answer: 2,
  why: "The manual says circular traffic signs alert drivers to upcoming railroad crossings.",
  ref: "Ch. 6, p. 28" },
{ cat: "Signs & Signals",
  q: "A sign shaped like a triangle with three equal sides tells you to do what?",
  options: [
    "Stop completely, then go",
    "Slow down and be prepared to stop and yield",
    "Merge left immediately",
    "Turn around, you are going the wrong way"
  ],
  answer: 1,
  why: "Three-sided signs warn drivers to slow down when approaching an intersection and be prepared to stop to yield to others.",
  ref: "Ch. 6, p. 28" },
{ cat: "Signs & Signals",
  q: "A pennant-shaped sign posted on the left side of a two-way road means what?",
  options: [
    "Passing is allowed here",
    "Do not pass other vehicles on the left",
    "A school bus stop is ahead",
    "The road narrows"
  ],
  answer: 1,
  why: "Pennant-shaped signs on the left side of two-way roads warn drivers not to pass other vehicles on the left.",
  ref: "Ch. 6, p. 28" },
{ cat: "Signs & Signals",
  q: "Fluorescent yellow-green signs are used to warn drivers about what?",
  options: [
    "Construction zones",
    "Nearby schools, pedestrians, bicycles, and playgrounds",
    "Speed limit changes",
    "Railroad crossings"
  ],
  answer: 1,
  why: "Fluorescent yellow-green signs warn of nearby schools, pedestrians, bicycles, playgrounds, and school bus routes.",
  ref: "Ch. 6, p. 27" },

/* ---------- SPEED LIMITS & FOLLOWING ---------- */
{ cat: "Speed Limits",
  q: "What is the maximum speed for a passenger car on a rural interstate highway in Indiana?",
  options: ["55 mph", "60 mph", "65 mph", "70 mph"],
  answer: 3,
  why: "On rural interstates, passenger vehicles may not exceed 70 mph or the posted speed limit.",
  ref: "Ch. 7, p. 40" },
{ cat: "Speed Limits",
  q: "A truck with a declared gross weight over 26,000 pounds is limited to what speed on a rural interstate?",
  options: ["55 mph", "60 mph", "65 mph", "70 mph"],
  answer: 2,
  why: "Trucks over 26,000 pounds may not exceed 65 mph on a rural interstate.",
  ref: "Ch. 7, p. 40" },
{ cat: "Speed Limits",
  q: "What is the speed limit on a rural state divided highway?",
  options: ["55 mph", "60 mph", "65 mph", "70 mph"],
  answer: 1,
  why: "On a rural state divided highway, vehicles may not exceed 60 mph or the posted limit.",
  ref: "Ch. 7, p. 40" },
{ cat: "Speed Limits",
  q: "In most urban residential areas, the speed limit is what?",
  options: ["15 mph", "25 mph", "30 mph", "35 mph"],
  answer: 2,
  why: "In most urban residential areas, vehicles may not exceed 30 mph or the posted limit.",
  ref: "Ch. 7, p. 40" },
{ cat: "Speed Limits",
  q: "What is the speed limit in an alley?",
  options: ["10 mph", "15 mph", "20 mph", "25 mph"],
  answer: 1,
  why: "In alleys, vehicles may not exceed 15 mph or the posted limit.",
  ref: "Ch. 7, p. 40" },
{ cat: "Speed Limits",
  q: "On urban interstates, non-divided state highways, and county roads, the limit is generally what?",
  options: ["45 mph", "50 mph", "55 mph", "60 mph"],
  answer: 2,
  why: "Urban interstates, non-divided state highways, and county roads are all limited to 55 mph or the posted limit.",
  ref: "Ch. 7, p. 40" },
{ cat: "Speed Limits",
  q: "When are school zone speed limits commonly in effect?",
  options: [
    "6 a.m. to 6 p.m., weekends only",
    "7 a.m. to 4:30 p.m., Monday through Friday",
    "Only when the crossing guard is present",
    "24 hours a day near any school"
  ],
  answer: 1,
  why: "Common school zone hours are 7 a.m. to 4:30 p.m., Monday through Friday, though local authorities may set lower limits whenever children are present.",
  ref: "Ch. 7, p. 41" },
{ cat: "Speed Limits",
  q: "Work site speed limits are always set at least how far below the area's maximum speed limit?",
  options: ["5 mph", "10 mph", "15 mph", "20 mph"],
  answer: 1,
  why: "Work site speed limits are always at least 10 mph below the maximum established speed limit for the area.",
  ref: "Ch. 7, p. 41" },
{ cat: "Speed Limits",
  q: "When not on an interstate or state highway, a school bus may not exceed what speed?",
  options: ["35 mph", "40 mph", "45 mph", "50 mph"],
  answer: 1,
  why: "Off interstates and state highways, the maximum for a school bus is 40 mph unless the posted limit is lower.",
  ref: "Ch. 7, p. 41" },
{ cat: "Speed Limits",
  q: "According to the manual, how far behind the vehicle ahead should you stay?",
  options: [
    "One car length per 10 mph",
    "At least two to three seconds",
    "At least five seconds",
    "One second in good weather"
  ],
  answer: 1,
  why: "Stay at least two to three seconds behind. Watch the car ahead pass a fixed object and count the time before you pass it.",
  ref: "Ch. 7, p. 41" },
{ cat: "Speed Limits",
  q: "At 65 mph, your car travels about 95 feet every second. About how long does it take to travel a football field at that speed?",
  options: ["About 3 seconds", "About 6 seconds", "About 10 seconds", "About 15 seconds"],
  answer: 0,
  why: "The manual's chart shows 3.1 seconds to travel a football field at 65 mph, which is why following distance matters so much.",
  ref: "Ch. 7, p. 41" },

/* ---------- SAFE DRIVING ---------- */
{ cat: "Safe Driving",
  q: "How far before turning or changing lanes must you signal?",
  options: [
    "50 feet",
    "100 feet",
    "200 feet, or 300 feet if the speed limit is 50 mph or more",
    "500 feet"
  ],
  answer: 2,
  why: "Signal at least 200 feet before turning or changing lanes, and at least 300 feet if the posted limit is 50 mph or more.",
  ref: "Ch. 7, p. 39" },
{ cat: "Safe Driving",
  q: "Your turn signal is broken. Can you use hand signals on the driving skills test?",
  options: [
    "Yes, hand signals are always fine",
    "Yes, but only for left turns",
    "No, hand signals may not be used on the driving skills exam",
    "Only if the examiner approves first"
  ],
  answer: 2,
  why: "Hand signals are allowed when lights malfunction, but the manual states you may not use hand signals on a driving skills exam.",
  ref: "Ch. 7, p. 39" },
{ cat: "Safe Driving",
  q: "A center lane marked for left turns may be used for what?",
  options: [
    "Passing slower vehicles",
    "Left turns only, never for passing",
    "Parking during off-peak hours",
    "Merging into traffic"
  ],
  answer: 1,
  why: "Center lanes are designated solely for left-turning vehicles. Never use them for passing.",
  ref: "Ch. 7, p. 39" },
{ cat: "Safe Driving",
  q: "Which statement about U-turns is true?",
  options: [
    "U-turns are fine on interstate highways",
    "Always yield to oncoming vehicles and pedestrians, and never make one on a curve, hill crest, or interstate",
    "U-turns never require a signal",
    "U-turns are allowed anywhere if no sign prohibits them"
  ],
  answer: 1,
  why: "Yield to oncoming traffic and pedestrians, never U-turn on a curve or the crest of a hill, and never on an interstate.",
  ref: "Ch. 7, p. 39" },
{ cat: "Safe Driving",
  q: "At a four-way stop, you and another driver arrive at the same time. Who goes first?",
  options: [
    "The driver on the left",
    "The driver going straight",
    "The driver to the right",
    "Whoever honks first"
  ],
  answer: 2,
  why: "First to stop goes first. If you arrive at the same time, the driver to the right has the right of way. When in doubt, yield.",
  ref: "Ch. 7, p. 39" },
{ cat: "Safe Driving",
  q: "In a roundabout, traffic flows in which direction?",
  options: [
    "Clockwise",
    "Counterclockwise",
    "Either direction",
    "The direction of the largest vehicle"
  ],
  answer: 1,
  why: "Roundabout traffic enters and exits only through right turns and proceeds counterclockwise. Incoming traffic always yields to circulating traffic.",
  ref: "Ch. 7, p. 40" },
{ cat: "Safe Driving",
  q: "In a multi-lane roundabout, two large trucks are driving through side by side. Who yields?",
  options: [
    "The truck in the left lane yields to the right",
    "The driver in the right lane yields to the driver in the left lane",
    "Neither, trucks always have the right of way",
    "Both must stop completely"
  ],
  answer: 1,
  why: "Drivers must yield to large vehicles in the roundabout. If two large vehicles are side by side, the right-lane driver yields to the left-lane driver.",
  ref: "Ch. 7, p. 40" },
{ cat: "Safe Driving",
  q: "Your car starts to skid and the rear wheels slide sideways. What should you do first?",
  options: [
    "Slam on the brakes",
    "Ease off the gas pedal",
    "Turn sharply away from the skid",
    "Shift into neutral"
  ],
  answer: 1,
  why: "Ease off the gas. Do not make a fast turn away from the skid and do not steer too far, which could cause a spin.",
  ref: "Ch. 7, p. 42" },
{ cat: "Safe Driving",
  q: "Your car has an anti-lock brake system (ABS). In a skid or emergency stop, you should do what?",
  options: [
    "Pump the brakes rapidly",
    "Keep firm, continuous pressure on the brake pedal and steer normally",
    "Take your foot off the brake completely",
    "Pull the parking brake"
  ],
  answer: 1,
  why: "With ABS, keep your foot on the brake with firm continuous pressure while steering normally. Do not pump. Vibration in the pedal means the ABS is working.",
  ref: "Ch. 7, p. 42" },
{ cat: "Safe Driving",
  q: "Your wheels drift onto the shoulder of the road. What is the safest response?",
  options: [
    "Jerk the wheel back onto the pavement immediately",
    "Brake hard, then turn sharply",
    "Ease off the gas, drive along the shoulder, then turn back gradually",
    "Speed up to get back on the road faster"
  ],
  answer: 2,
  why: "Do not turn back right away or you could lose balance. Ease up on the gas, drive along the shoulder, then turn back gradually after slowing.",
  ref: "Ch. 8, p. 58" },
{ cat: "Safe Driving",
  q: "Rollover crashes account for about how many passenger vehicle fatalities?",
  options: [
    "Nearly one-tenth",
    "Nearly one-third",
    "Nearly one-half",
    "Nearly all of them"
  ],
  answer: 1,
  why: "Rollover crashes account for nearly one-third of all passenger vehicle fatalities, so avoid panicked overcorrecting.",
  ref: "Ch. 7, p. 42" },
{ cat: "Safe Driving",
  q: "Fuel consumption increases steadily above what speed?",
  options: ["35 mph", "45 mph", "55 mph", "65 mph"],
  answer: 1,
  why: "Fuel consumption rises steadily above 45 mph. Cars use about 50 percent more fuel at 75 mph than at 55 mph.",
  ref: "Ch. 7, p. 42" },
{ cat: "Safe Driving",
  q: "Tires can lose up to 1 psi per month. How often should you check tire pressure?",
  options: [
    "Once a year",
    "Once a month, including the spare",
    "Only before winter",
    "Only when a tire looks flat"
  ],
  answer: 1,
  why: "Check all tires, including the spare, once a month or before a long trip, and check them cold.",
  ref: "Ch. 7, p. 43" },

/* ---------- EMERGENCIES & ACCIDENTS ---------- */
{ cat: "Emergencies",
  q: "A collision looks unavoidable. The manual says you have three options. Which is NOT one of them?",
  options: [
    "Stop quickly",
    "Turn quickly",
    "Speed up",
    "Close your eyes"
  ],
  answer: 3,
  why: "The manual lists three options: stop quickly, turn quickly, or speed up. Accelerating is sometimes the best or only way to avoid a collision.",
  ref: "Ch. 8, p. 58" },
{ cat: "Emergencies",
  q: "If you must hit something, what should you choose?",
  options: [
    "Something hard, like a tree",
    "Something that will give way, like brush or shrubs",
    "Oncoming traffic",
    "A parked car"
  ],
  answer: 1,
  why: "Choose to hit something that will give way, like brush, rather than something hard. It is safer to hit something not moving than to hit something head-on.",
  ref: "Ch. 8, p. 58" },
{ cat: "Emergencies",
  q: "Your vehicle plunges into water. What should you do first?",
  options: [
    "Try to force the door open",
    "Remove your seat belt and open a window",
    "Wait for the car to fill with water",
    "Climb into the trunk"
  ],
  answer: 1,
  why: "Remove your seat belt and open a window. The car will float several minutes. Do not open a door; water pressure makes it nearly impossible.",
  ref: "Ch. 8, p. 59" },
{ cat: "Emergencies",
  q: "After escaping a vehicle in water, where should you go?",
  options: [
    "Back inside for your phone",
    "Swim away immediately",
    "Exit to the roof, call 911, and look for dry land",
    "Stay in the back seat"
  ],
  answer: 2,
  why: "Exit and move to the roof, call 911, and locate dry land. Swim for shore only as a last resort, and never reenter for possessions.",
  ref: "Ch. 8, p. 59" },
{ cat: "Emergencies",
  q: "What are the main factors that determine a person's blood alcohol concentration?",
  options: [
    "Height and eye color",
    "Amount of alcohol, how fast it was consumed, and body weight",
    "The type of car being driven",
    "Time of day"
  ],
  answer: 1,
  why: "BAC depends on the amount consumed, how quickly it was consumed, and the person's body weight.",
  ref: "Ch. 8, p. 59" },
{ cat: "Emergencies",
  q: "Which is a sign of an impaired driver?",
  options: [
    "Driving exactly at the speed limit",
    "Straddling the center line or weaving",
    "Using turn signals properly",
    "Keeping a steady following distance"
  ],
  answer: 1,
  why: "The manual lists straddling the center line or weaving, wide turns, unusual speed, near misses, and driving at night without headlights as signs of impairment.",
  ref: "Ch. 8, p. 59" },
{ cat: "Emergencies",
  q: "You have a blowout. What should you do?",
  options: [
    "Brake hard immediately",
    "Hold the wheel firmly, keep straight, ease off the gas, and do not brake",
    "Turn sharply toward the shoulder",
    "Speed up to stabilize the car"
  ],
  answer: 1,
  why: "Hold the steering wheel firmly, keep the car going straight, take your foot off the gas but do not brake. Pull off the road, then brake when almost stopped.",
  ref: "Ch. 8, p. 60" },
{ cat: "Emergencies",
  q: "Your brakes suddenly fail. What should you try first?",
  options: [
    "Turn off the ignition immediately",
    "Shift to a lower gear and pump the brake pedal fast and hard",
    "Open the door to slow down",
    "Put the car in park"
  ],
  answer: 1,
  why: "Shift to a lower gear and pump the brake pedal fast and hard several times to build pressure. You can also try the parking brake while holding the release.",
  ref: "Ch. 8, p. 60" },
{ cat: "Emergencies",
  q: "Why should you never turn the ignition to the lock position while the car is moving?",
  options: [
    "It drains the battery",
    "The steering will lock and you will lose control",
    "It disables the horn",
    "It is only illegal at night"
  ],
  answer: 1,
  why: "With a steering wheel interlock system, turning the ignition to lock while moving locks the steering as the wheel turns, causing loss of control.",
  ref: "Ch. 8, p. 60" },
{ cat: "Emergencies",
  q: "For a roadside emergency at night, where should you place your reflective triangle?",
  options: [
    "Right behind the bumper",
    "200 feet behind the vehicle, or 500 feet on a hill or curve",
    "Inside the car on the dashboard",
    "It does not matter"
  ],
  answer: 1,
  why: "Place the triangle 200 feet behind your vehicle, or 500 feet behind if you are on a hill or curve.",
  ref: "Ch. 8, p. 60" },
{ cat: "Emergencies",
  q: "You are pulled over by police at night. What should you do?",
  options: [
    "Get out and walk to the patrol car",
    "Stay inside, turn on the interior light, and keep your hands on the wheel",
    "Argue about why you were stopped",
    "Refuse to sign the ticket"
  ],
  answer: 1,
  why: "Remain inside unless directed otherwise, turn on the interior light at night, and keep hands visible. Signing a ticket is not an admission of guilt.",
  ref: "Ch. 8, p. 61" },
{ cat: "Emergencies",
  q: "An officer asks for your license, but it is in the glove box. What should you do?",
  options: [
    "Reach for it quickly before the officer approaches",
    "Tell the officer where it is and follow directions before reaching for it",
    "Say you do not have it",
    "Hand over your phone instead"
  ],
  answer: 1,
  why: "If documents are in the glove box or under the seat, inform the officer first, then follow directions before reaching to retrieve them.",
  ref: "Ch. 8, p. 61" },
{ cat: "Emergencies",
  q: "Carbon monoxide is dangerous because you cannot do what?",
  options: [
    "See it, smell it, or taste it",
    "Hear it",
    "Feel it in the steering wheel",
    "Measure it with a tire gauge"
  ],
  answer: 0,
  why: "You cannot see, smell, or taste carbon monoxide. Watch for drowsiness, dizziness, headache, or a bluish tinge to skin or lips.",
  ref: "Ch. 8, p. 62" },
{ cat: "Emergencies",
  q: "What is one way to avoid carbon monoxide poisoning?",
  options: [
    "Run the engine in a closed garage to warm it up",
    "Never let the engine run in a closed garage",
    "Ignore a loud roar from under the car",
    "Keep the fresh-air vent closed on highways in winter"
  ],
  answer: 1,
  why: "Never let your vehicle run in a closed garage. Also have the exhaust checked regularly and watch for unusual roars.",
  ref: "Ch. 8, p. 62" },

/* ---------- RULES, POINTS & PENALTIES ---------- */
{ cat: "Rules & Penalties",
  q: "How many points is 10 mph over the speed limit worth?",
  options: ["2 points", "4 points", "6 points", "8 points"],
  answer: 0,
  why: "1 to 15 mph over the limit is 2 points. It jumps to 4 points at 16 to 25 over, and 6 points at 26 or more over.",
  ref: "Ch. 5, p. 21" },
{ cat: "Rules & Penalties",
  q: "How many points do you get for following another vehicle too closely?",
  options: ["2 points", "4 points", "6 points", "8 points"],
  answer: 2,
  why: "Following too closely is 6 points, as is failing to yield to an emergency vehicle.",
  ref: "Ch. 5, p. 21" },
{ cat: "Rules & Penalties",
  q: "How many points is driving while suspended worth?",
  options: ["4 points", "6 points", "8 points", "10 points"],
  answer: 2,
  why: "Driving while suspended is 8 points, one of the most serious point violations listed.",
  ref: "Ch. 5, p. 21" },
{ cat: "Rules & Penalties",
  q: "How long do points stay active on your Indiana driving record?",
  options: [
    "Six months",
    "One year",
    "Two years from the conviction date",
    "Forever"
  ],
  answer: 2,
  why: "Points stay active on your driver record for two years from the conviction date.",
  ref: "Ch. 5, p. 21" },
{ cat: "Rules & Penalties",
  q: "A BMV-approved Driver Safety Program course gives you what benefit?",
  options: [
    "A four-point credit, allowed once every three years",
    "A free license renewal",
    "Lower speed limits",
    "An extra license"
  ],
  answer: 0,
  why: "Any Indiana driver may earn a four-point credit from a BMV-approved DSP, limited to one credit per three-year period. Max fee is $55.",
  ref: "Ch. 5, p. 21" },
{ cat: "Rules & Penalties",
  q: "What is Indiana's minimum liability insurance standard?",
  options: [
    "10/20/10",
    "25/50/25",
    "50/100/50",
    "100/300/100"
  ],
  answer: 1,
  why: "Indiana requires $25,000 per person, $50,000 per accident for bodily injury or death, and $25,000 for property damage. Shorthand: 25/50/25.",
  ref: "Ch. 5, p. 22" },
{ cat: "Rules & Penalties",
  q: "If you are caught driving without the minimum insurance, how long can your suspension last?",
  options: [
    "30 to 60 days",
    "90 days to one year",
    "Two to five years",
    "There is no suspension, only a warning"
  ],
  answer: 1,
  why: "Penalties include reinstatement fees and suspensions ranging from 90 days to one year.",
  ref: "Ch. 5, p. 22" },
{ cat: "Rules & Penalties",
  q: "A driver with a previous OWI conviction refuses a chemical test. How long is the suspension?",
  options: [
    "90 days",
    "One year",
    "Two years",
    "Six months"
  ],
  answer: 2,
  why: "A motorist with a previous OWI conviction who refuses a chemical test faces a two-year suspension.",
  ref: "Ch. 5, p. 24" },
{ cat: "Rules & Penalties",
  q: "What is the penalty for operating a watercraft while intoxicated?",
  options: [
    "Only a fine, no license impact",
    "The same penalties as operating a motor vehicle while intoxicated",
    "A warning for a first offense",
    "Community service only"
  ],
  answer: 1,
  why: "A watercraft OWI carries the same penalties as a motor vehicle OWI and goes on your driver record.",
  ref: "Ch. 5, p. 24" },
{ cat: "Rules & Penalties",
  q: "A Habitual Traffic Violator with three major offenses in 10 years faces what suspension?",
  options: [
    "One year",
    "Five years",
    "Ten years",
    "Thirty days"
  ],
  answer: 2,
  why: "Three major offenses (like OWI, reckless driving, or drag racing) in 10 years brings a 10-year suspension.",
  ref: "Ch. 5, p. 25" },
{ cat: "Rules & Penalties",
  q: "If you are 21 or older with six or more active points, what must you do to renew your license?",
  options: [
    "Pay double the fee",
    "Take the knowledge exam",
    "Retake the driving skills test",
    "Wait an extra year"
  ],
  answer: 1,
  why: "Drivers 21 or older with six or more active points must take the knowledge exam to renew.",
  ref: "Ch. 4, p. 19" },

/* ---------- TEENS & PERMITS ---------- */
{ cat: "Teens & Permits",
  q: "How old must you be to get an Indiana learner's permit?",
  options: ["14", "15", "15 and 180 days", "16"],
  answer: 3,
  why: "You must be at least 16 years old and pass the vision screening and the written knowledge test based on this manual.",
  ref: "Ch. 1, p. 3" },
{ cat: "Teens & Permits",
  q: "If you are under 18, what else is required on a learner's permit application?",
  options: [
    "A parent must take the test with you",
    "An appropriate adult must sign the financial responsibility agreement",
    "You must own a car first",
    "Nothing extra"
  ],
  answer: 1,
  why: "If you are under 18, an appropriate adult must sign the financial responsibility agreement on the application.",
  ref: "Ch. 1, p. 3" },
{ cat: "Teens & Permits",
  q: "You completed driver education and held your permit for 60 days. How old must you be for an operator's license?",
  options: [
    "16 years and 30 days",
    "16 years and 180 days",
    "17 years",
    "18 years"
  ],
  answer: 0,
  why: "With a completed driver education course and a permit held 60 days, you may apply at 16 years and 30 days. Without driver ed, it is 16 years and 180 days.",
  ref: "Ch. 1, p. 8" },
{ cat: "Teens & Permits",
  q: "How many total exams (written and driving combined) may you fail when applying for an operator's license?",
  options: ["One", "Two", "No more than three", "Unlimited"],
  answer: 2,
  why: "You may fail no more than three examinations total. If one of your first two failures is a drive test, you must wait 14 days before another drive test.",
  ref: "Ch. 1, p. 8" },
{ cat: "Teens & Permits",
  q: "You just moved to Indiana. How long do you have to get an Indiana driver's license?",
  options: ["30 days", "60 days", "90 days", "One year"],
  answer: 1,
  why: "New Indiana residents have 60 days to obtain an Indiana driver's license.",
  ref: "Ch. 1, p. 2" },
{ cat: "Teens & Permits",
  q: "You move to a new address. How soon must you notify the BMV?",
  options: [
    "Within 10 days",
    "Within 30 days",
    "Within 60 days",
    "At your next renewal"
  ],
  answer: 1,
  why: "You must notify the BMV of a principal address change and apply for an amended credential within 30 days.",
  ref: "Ch. 4, p. 20" },
{ cat: "Teens & Permits",
  q: "According to the manual, what is the most common contributing factor in teen crashes?",
  options: [
    "Bad weather",
    "Errant and risky driving plus distraction",
    "Car trouble",
    "Driving at night"
  ],
  answer: 1,
  why: "The manual says errant and risky driving and distraction is the most common contributing factor in teen crashes.",
  ref: "App. B, p. 69" },
{ cat: "Teens & Permits",
  q: "What happens to crash risk when a teen drives with passengers?",
  options: [
    "It stays the same",
    "It drops because of extra eyes",
    "It only matters at night",
    "It doubles with each passenger present"
  ],
  answer: 3,
  why: "The manual warns that the chance of a crash doubles with each passenger in the vehicle.",
  ref: "App. B, p. 69" },
{ cat: "Teens & Permits",
  q: "Where do most multi-vehicle crashes involving teens happen?",
  options: [
    "On interstates",
    "In parking lots",
    "At intersections",
    "On rural roads"
  ],
  answer: 2,
  why: "Most multi-vehicle crashes involving teens occur at intersections, so stay focused on other vehicles there.",
  ref: "App. B, p. 69" },
{ cat: "Teens & Permits",
  q: "What does the manual say about using your phone while driving?",
  options: [
    "It is fine at stoplights",
    "Do not talk or text while driving, it is against the law",
    "Hands-free is encouraged",
    "Only passengers may not use phones"
  ],
  answer: 1,
  why: "The teen tips say plainly: do not talk on the phone or text while driving, it is against the law.",
  ref: "App. B, p. 70" },
{ cat: "Teens & Permits",
  q: "You approach a green light at an intersection. What should you be ready for?",
  options: [
    "Nothing, green always means go",
    "To stop in case the light changes",
    "To speed up to beat the yellow",
    "To honk at pedestrians"
  ],
  answer: 1,
  why: "Always be prepared to stop as you approach an intersection with a green light in case it changes. Do not enter after it turns yellow unless you are already in the intersection.",
  ref: "App. B, p. 70" },
{ cat: "Teens & Permits",
  q: "A driver under 18 operating an off-road vehicle must wear what?",
  options: [
    "A reflective vest",
    "A helmet meeting U.S. DOT standards",
    "Sunglasses",
    "Steel-toed boots"
  ],
  answer: 1,
  why: "Anyone under 18 operating or riding an ORV must wear a helmet meeting U.S. Department of Transportation standards.",
  ref: "App. B, p. 70" },
{ cat: "Teens & Permits",
  q: "A star in the upper right corner of your credential means what?",
  options: [
    "You are an organ donor",
    "The credential is Real ID compliant",
    "You have a motorcycle endorsement",
    "You are under 21"
  ],
  answer: 1,
  why: "A star marker in the upper right corner indicates the credential is Real ID compliant for federal purposes.",
  ref: "Ch. 1, p. 1" }
];
